import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import folium_static
import matplotlib.pyplot as plt
import pandas as pd



st.set_page_config(
    page_title="Airbnb in Spanish cities",
    page_icon="🏠",
    layout="wide",
)
cities = pd.read_json('data/cities.json', lines=True)
city_list = [x.capitalize() for x in cities.city.tolist()]

st.title("Percentage of Airbnb's")
st.text("You can select different cities and types of Airbnb rentals to explore the data and see how much housing"
         " is devoted to Airbnb in different places. Hover over the map to get a result."
         )
# Division selection
city = st.selectbox("Select a city", options=city_list)
# Type selection
type = st.selectbox("Select a type of Airbnb rental", options=["All", "Full aparments", "Rooms"])

if type == "Full aparments":
    col = 'ratio_flats'
elif type == "Rooms":
    col = 'ratio_rooms'
elif type == "All":
    col = 'ratio'

gdf =gpd.read_file(f'data/results/{city.lower()}.geojson')
# Ensure unique index for matching
gdf = gdf.reset_index(drop=True)
gdf.index.name = 'id'  # Choropleth will use this as feature.id
gdf[col] = gdf[col].astype(float).round(1) # Ensure the column is float and rounded to 1 decimal place

location = gdf.iloc[gdf['ratio'].idxmax()].geometry.centroid

# Create Folium map
m = folium.Map(
    location=[location.y, location.x],
    zoom_start=13,
    tiles='CartoDB positron'
)


# Add choropleth
folium.Choropleth(
    geo_data=gdf,
    data=gdf,
    columns=[gdf.index, col],
    key_on='feature.id',
    fill_color='Reds',
    fill_opacity=0.5,
    line_opacity=0.2,
    legend_name='Percentage of Airbnb',
    highlight=True,
).add_to(m)

folium.GeoJson(
    gdf,
    tooltip=folium.GeoJsonTooltip(fields=[col], aliases=["%:"]),
    style_function=lambda feature: {
        'fillOpacity': 0,
        'color': 'transparent'
    }
).add_to(m) # Add GeoJson for tooltips

folium_static(m, width=1000, height=500)


st.write("")
st.write("")
st.text("We can get a deeper insight into those zones of Barcelona with a higher percentage of airbnbs by zooming in the map and focusing only "
                "on those censal sections with a percentage higher than 5%, where we have overimposed the street network of Barcelona for better visualization."
                "\n\nNote how some cultural landmarks like the Sagrada Familia, Plaça Catalunya, La Barceloneta, and Montjuïc are hotspots for Airbnb rentals."
                " This is a clear indication of the impact of tourism in these areas, which are often the most attractive for visitors."
                " This map can be used to identify areas where the concentration of Airbnb rentals is particularly high, "
                "which can help in understanding the dynamics of tourism and housing in Barcelona."
                "\n\nThose areas with a high concentration of Airbnb rentals can be considered as 'parasites' in the sense that they are taking away apartments from local residents,"
                " leading to a decrease in the availability of affordable housing for locals." )

st.markdown("### Methodology:\n\nThese results have been generated by counting the number of Airbnb rentals in each censal section and dividing it by the total number of houses/apartments in that section."
        " All data is open access. Housing data can be obtained from the [Spanish cadaster Inspire system](https://www.catastro.hacienda.gob.es/webinspire/index.html),"
        " while Airbnb data is available through the [Inside Airbnb project](http://insideairbnb.com/get-the-data.html). The dataset used here includes all "
        "Airbnb listings in Barcelona in the period January-March 2025. The street network was obtained from [OpenStreetMap](https://www.openstreetmap.org/]) using the [OSMnx library](https://osmnx.readthedocs.io/)."
        "\n\nAll code is available on [GitHub](https://github.com/mehrrero/parasites) and has been developed by [**Míriam Herrero, PhD**](https://www.linkedin.com/in/m-herrero-valea/)."
        )